name: "Check PR Title"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Validate PR Title
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^(Feature|Bugfix|Hotfix|Chore):\ .+ ]]; then
            echo "❌ PR title does not follow the correct format (e.g., 'Feature: ...', 'Bugfix: ...')."
            exit 1
          fi
        shell: bash
